### ISSUE TITLE
factoids-ref in Person schema serialized object rather than pointer

### ISSUE THREAD

**Issue by sennierer** [GVogeler/prosopogrAPhI#19]
Is it intended that here: https://github.com/GVogeler/prosopogrAPhI/blob/1e9534ee1d43f9bdb5afce731e18ad3d94367966/prosopogrAPhI.yaml#L756-L759 we do not point to the factoids (like we do it normally), but rather include a serialization of them?

**Comment by GVogeler** [comment]
Well, not really serialising them, but using them as a container for further pointers. This would make clear, that these pointers are not affected by the filter of the original resource (/person/?filter=X returns a list of persons filtered by X and the factoids refering to the persons. These factoids are entities independent from the original resource. Does this make sense?

**Comment by GVogeler** [comment]
and it would spare us one additional call for retrieving the identifiers of the resources linked to the original resource via the factoid intermediate.

**Comment by sennierer** [comment]
yes,  my fault, thought it was a full serialization.
